---
- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Ensure SSH port is registered in /etc/services
      lineinfile:
        path: /etc/services
        regexp: ^ssh
        line: "ssh\t\t54223/tcp\t\t\t# SSH Remote Login Protocol"
    - name: Ensure fail2ban is installed
      ansible.builtin.apt:
        name: fail2ban
        state: latest
