---
- hosts: ts3servers
  become: true
  become_user: root
  vars:
    teamspeak_container_name: teamspeak
    teamspeak_container_image: teamspeak
  tasks:
    - name: Ensure necessary packages are installed
      ansible.builtin.apt:
        name: 
          - docker-ce
          - pip
        state: present
    # Installs Docker Module for Python.
    # Allows you to manage Docker containers from within Ansible playbooks.
    - name: Ensure Docker Module for Python is installed
      pip:
        name: docker
    # Pulls the default docker image (Ubuntu)
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ teamspeak_container_image }}"
        source: pull
        tag: latest
    - getent:
        database: passwd
    # Create container
    - name: Ensure teamspeak container is running
      community.docker.docker_container:
        name: "{{ teamspeak_container_name }}"
        image: "{{ teamspeak_container_image }}"
        published_ports:
          - "9987:9987/udp"
          - "10011:10011"
          - "30033:30033"
        env:
          TS3SERVER_LICENSE: accept
        volumes:
          - 'ts3data:/var/ts3server'
        restart_policy: always
        state: started

