---
- hosts: desktops
  become: true
  become_user: root
  tasks:
    - name: Install necessary packages on arch desktops
      when: ansible_os_family == 'Archlinux'
      pacman:
        name: 
          - plasma
          - plasma-wayland-session
          - pipewire
          - pipewire-pulse
          - steam
          - mesa
          - firefox
          - kdeconnect
          - thunderbird
          - teamspeak3
          - canon-pixma-mg5700-complete
          - brscan4
          - brscan5
          - zathura
          - obs-studio
          - libreoffice-fresh
          - keepassxc
          - telegram-desktop
          - xsane
        state: latest
    - name: Install necessary flatpaks
      flatpak:
        name:
          - org.gimp.GIMP
          - org.kde.kdenlive
          - org.videolan.VLC
          - org.godotengine.Godot
        state: latest
