---
- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install necessary packages on Debian/Ubuntu servers
      ansible.builtin.apt:
        name: 
          - ansible
          - zsh
          - glances
          - curl # für docker-ce
          - ca-certificates # für docker-ce
          - openjdk-19-jdk # für minecraft
        state: present
    - name: Ensure minecraft user exists
      ansible.builtin.user:
        name: minecraft
    - name: Ensure ts3 user exiss
      ansible.builtin.user:
        name: ts3
        state: absent
