---
- hosts: sinusbot
  become: true
  become_user: root
  vars:
    sinusbot_user: sinusbot
    sinusbot_container_name: sinusbot
    sinusbot_container_image: sinusbot/docker
  tasks:
    - name: Ensure sinusbot user exists
      ansible.builtin.user:
        name: '{{ sinusbot_user }}'
    - name: Ensure necessary packages are installed
      ansible.builtin.apt:
        name: 
          - docker-ce
          - pip
        state: present
    # Installs Docker Module for Python.
    # Allows you to manage Docker containers from within Ansible playbooks.
    - name: Ensure Docker Module for Python is installed
      pip:
        name: docker
    # Pulls the default docker image (Ubuntu)
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ sinusbot_container_image }}"
        source: pull
        tag: latest
    - getent:
        database: passwd
    # Create container
    - name: Ensure Sinusbot container is running
      community.docker.docker_container:
        name: "{{ sinusbot_container_name }}"
        image: "{{ sinusbot_container_image }}"
        published_ports:
          - "8087:8087"
        volumes:
          - 'sinusbot_scripts:/opt/sinusbot/scripts'
          - 'sinusbot_data:/opt/sinusbot/data'
        env:
          OVERRIDE_PASSWORD: '{{ sinusbot_password }}'
          UID: "{{ getent_passwd[sinusbot_user].1 }}"
          GID: "{{ getent_passwd[sinusbot_user].2 }}"
        restart_policy: always
        state: started

