---
- name: Ensure docker packages are installed
  ansible.builtin.apt:
    name: 
      - docker-ce
      - pip
    state: present
# Installs Docker Module for Python.
# Allows you to manage Docker containers from within Ansible playbooks.
- name: Ensure Docker Module for Python is installed
  pip:
    name: docker
