---
- hosts: container-backup
  become: true
  become_user: root
  tasks:
    - name: Ensure cronic is installed
      ansible.builtin.apt:
        name: cronic
        state: latest
    # Copy Dockerfile
    - name: Copy Dockerfile
      ansible.builtin.copy:
        src: files/Dockerfile
        dest: /tmp/container-backup/
        mode: "775"
    # Schedule backup script every monday morning
    # Copy backup script
    - name: Copy backup script
      ansible.builtin.copy:
        src: files/backup-container.sh
        dest: /var/backup
        mode: "775"
    - name: Build the container backup image
      community.docker.docker_image:
        name: container-backup
        build:
          path: /tmp/container-backup
        source: build
