---
- hosts: foundryvtt
  become: true
  become_user: root
  vars:
    foundryvtt_container_name: foundryvtt
    foundryvtt_container_image: docker.io/felddy/foundryvtt
    foundryvtt_user: foundryvtt
  tasks:
    - name: Ensure FoundryVTT user exists
      ansible.builtin.user:
        name: "{{ foundryvtt_user }}"
    - name: Ensure necessary packages are installed
      ansible.builtin.apt:
        name: 
          - docker-ce
          - pip
        state: present
    # Installs Docker Module for Python.
    # Allows you to manage Docker containers from within Ansible playbooks.
    - name: Ensure Docker Module for Python is installed
      pip:
        name: docker
    # Pulls the default docker image (Ubuntu)
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ foundryvtt_container_image }}"
        source: pull
    # Create container
    - name: Ensure Foundry VTT container is running
      become_user: foundryvtt
      containers.podman.podman_container:
        name: "{{ foundryvtt_container_name }}"
        image: "{{ foundryvtt_container_image }}"
          #        user: "{{ foundryvtt_user }}"
        published_ports:
          - "30000:30000/tcp"
        env:
          FOUNDRY_USERNAME: '{{ foundryvtt_username }}'
          FOUNDRY_PASSWORD: '{{ foundryvtt_password }}'
          FOUNDRY_ADMIN_KEY: '{{ foundryvtt_admin_key }}'
        volumes:
          - 'foundryvtt:/data'
        restart_policy: always
        state: started

