---
- hosts: influxdb
  become: true
  become_user: root
  vars:
    influxdb_container: influxdb
    influxdb_image: influxdb
  tasks:
    - name: Ensure container is running
      community.docker.docker_container:
        name: "{{ influxdb_container }}"
        image: "{{ influxdb_image }}"
        volumes:
          - "influxdb:/var/lib/influxdb2"
        published_ports:
          - "8086:8086"
        restart_policy: always
        state: started

