---
- hosts: minecraftservers
  become: true
  become_user: root
  vars:
    minecraft_container_name: minecraft
    minecraft_container_image: itzg/minecraft-server
    minecraft_user: minecraft
  tasks:
    # Schedule backup script
    - name: Schedule backup
      ansible.builtin.cron:
        name: "backup minecraft"
        hour: "3"
        minute: "0"
        user: root
        job: "cronic /var/backup/backup-container.sh {{ minecraft_container_name }} /data"
    # Pulls the default docker image (Ubuntu)
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ minecraft_container_image }}"
        source: pull
        tag: latest
    - getent:
        database: passwd
    # Create container
    - name: Ensure minecraft container is running
      community.docker.docker_container:
        name: "{{ minecraft_container_name }}"
        image: "{{ minecraft_container_image }}"
        published_ports:
          - "25565:25565"
        env:
          EULA: "TRUE"
          UID: "{{ getent_passwd[minecraft_user].1 }}"
          GID: "{{ getent_passwd[minecraft_user].2 }}"
          user: minecraft:minecraft
          MEMORY: 4G
        volumes:
          - 'minecraft:/data'
        restart_policy: always
        state: started

