---
- hosts: steamservers
  become: true
  become_user: root
  vars:
    csgo_container_name: csgo
    steam_container_image: cm2network/csgo
    steam_user: steam
    csgo_install_dir: /data/
  tasks:
    - name: Ensure Steam user exists
      ansible.builtin.user:
        name: "{{ steam_user }}"
    - name: Ensure necessary packages are installed
      ansible.builtin.apt:
        name: 
          - docker-ce
          - pip
        state: present
    # Installs Docker Module for Python.
    # Allows you to manage Docker containers from within Ansible playbooks.
    - name: Ensure Docker Module for Python is installed
      pip:
        name: docker
    # Pulls the default docker image (Ubuntu)
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ steam_container_image }}"
        source: pull
    - getent:
        database: passwd
    # Create container
    - name: Ensure Steam container is running
      community.docker.docker_container:
        name: "{{ csgo_container_name }}"
        image: "{{ steam_container_image }}"
        command: >
          bash -c "/home/steam/steamcmd/steamcmd.sh 
                    +force_install_dir {{ csgo_install_dir }} 
                    +login anonymous 
                    +app_update 740"
        user: steam:steam
        env:
          SRCDS_TOKEN: "1825CDDF5AD052F35272D113D9ECB911"
          SRCDS_PW: 'kätzchen'
          SRCDS_RCONPW: 'kätzchen'
        published_ports:
          - "27015:27015"
          - "27036:27036/tcp"
          - "27020:27020/udp"
          - "27031-27036:27031-27036/udp"
        restart_policy: always
        state: started

